### ISSUE TITLE
Easier preview of multi-stage activities

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#1022]
Trying to develop a multi-stage activity, like the Train Activity, is frustrating - when you are working on a specific interface, it might take you a lot of time to get back to it whenever you make a change, and it reloads.

Perhaps we could have an extra argument in the exampleData, which gets picked up by the renderer, and let's us directly jump to specific parts or states of the application in Preview.

**Comment by prastut** [comment]
Merged in #1023
