### ISSUE TITLE
[Repository] Display list of Orchestration Graphs

### ISSUE THREAD

**Issue by lfaucon** [chili-epfl/FROG#11]
- [x]  Give choice between list of activities or list of orchestration graphs
- [x]  display a clickable list of orchestration graphs
- [x]  on click display graphically the structure of the graph

**Comment by lfaucon** [comment]
@palexlee:
As you have been looking at a few external libraries. Could you give us a short list and tell us which one you decided to use and why? (answer on this issue)

**Comment by palexlee** [comment]
**Highcharts :** It allows to do general drawing, especially drawing boxes and arrows to build a directed graph. It's the one I've been using, but I'm afraid the result won't be as clean as other solutions.

**D3 :** Seems to be more harder to use than Highcharts.

**Google Chart - Gantt :**Looks exactly to what I need, I can link activities with arrows, but it doesn't allow to have more than one activity on the same row (on the same plane).

**Google Chart - Timeline :**Allow to put more than one activity on the same row, but cannot draw arrows.

**AnyGantt :** Seems to be a better solution than Google Chart Timeline/Gantt.

For the moment, I'm investigating AnyGantt and still looking for other libraries. I'll take a deeper look at D3 and if it is too hard to use, I'll have to continue with Highcharts.
