### ISSUE TITLE
Progress dashboard generates too much data over long time

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#1103]
This graph currently takes 172 kb to render. Unfortunately, this data is sent once a second (assuming there is any new updates), obviously incredibly inefficient. Seems primarily related to the number of seconds since the start of the activity, not the number of students. I understand that we designed progress for activities lasting minutes, but we should make it robust for activities lasting hours - perhaps prepareData can measure the length of the activity and scale the time buckets dynamically, for example.

<img width="562" alt="screen shot 2018-04-30 at 21 42 37" src="https://user-images.githubusercontent.com/61575/39446726-b6565f52-4cbf-11e8-82c3-a02af51c370d.png">

<img width="535" alt="screen shot 2018-04-30 at 21 45 00" src="https://user-images.githubusercontent.com/61575/39446735-c273c9f0-4cbf-11e8-96e3-2fee1beeeddf.png">

**Comment by Jiaxigu** [comment]
A very good catch, will fix.
