### ISSUE TITLE
Preview full-screen mode single activity hides top

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#1126]
If you have a single activity open in preview, and you go to full-screen mode, the top of the activity is overlaid by the top bar.

Compare below.

There is also something weird about the container for the activity (the modal-body or whatever) - it's at 85% of the screen height for some reason - even more clear when you do full-screen. If I do height=100% in my component (for example ac-textarea) I get a scroll-bar, not sure how I should get this to fill the area but not overflow? And don't know why we need the 30 or so pixels at the bottom of the screen?

<img width="1390" alt="screen shot 2018-05-08 at 18 50 08" src="https://user-images.githubusercontent.com/61575/39770887-aa5f5ea6-52f0-11e8-8b98-9f5827bc7dd4.png">
<img width="1335" alt="screen shot 2018-05-08 at 18 50 04" src="https://user-images.githubusercontent.com/61575/39770888-aa78e790-52f0-11e8-8fcb-df32d792238f.png">

**Comment by prastut** [comment]
> There is also something weird about the container for the activity (the modal-body or whatever) - it's at 85% of the screen height for some reason - even more clear when you do full-screen. If I do height=100% in my component (for example ac-textarea) I get a scroll-bar, not sure how I should get this to fill the area but not overflow? And don't know why we need the 30 or so pixels at the bottom of the screen?

Fixed. Now you don't have 30 pixels as well at the bottom of the screen as well :D
