### ISSUE TITLE
Cannot select an activity

### ISSUE THREAD

**Issue by lfaucon** [chili-epfl/FROG#114]
On a new graph If I create two simultaneous activities, it becomes impossible to select the top activity.

![screenshot from 2017-03-28 10-08-46](https://cloud.githubusercontent.com/assets/8818081/24395081/a2beefd2-139e-11e7-8519-ceb5f5462b66.png)

**Comment by houshuang** [comment]
I think it's because the dragGuides are rendered on top of the activity, and prevent the click from being picked up by the activity... Probably we should just not render drag-guides when overlap is allowed.

**Comment by houshuang** [comment]
Assigning to @lfaucon
