### ISSUE TITLE
Visual Upgrade

### ISSUE THREAD

**Issue by prastut** [chili-epfl/FROG#1148]
- [ ] Learning Items Visual Fixing

PR: https://github.com/chili-epfl/FROG/pull/1136

Video Link: https://www.youtube.com/watch?v=Zt6mkEW0XbM

Screenshots (with time so that you know where to scrub to) that need fixing: 

![image](https://user-images.githubusercontent.com/10279686/40003319-4fbc1d84-5793-11e8-8845-ab74cb5f6294.png)

Modals in general in FROG need visual love. Mainly ported to: https://material-ui-next.com/demos/dialogs/. (padding, alignment, padding with header with type fixes, action button placement)

![image](https://user-images.githubusercontent.com/10279686/40003408-8a1d6f6e-5793-11e8-9447-5f14902b25d2.png)

![image](https://user-images.githubusercontent.com/10279686/40003414-8d853010-5793-11e8-80b3-4920d58b9e51.png)

![image](https://user-images.githubusercontent.com/10279686/40003424-9492e000-5793-11e8-8d31-b78e9dea0913.png)

The files could be reduced to icons with names etc.

**Comment by prastut** [comment]
- [ ] Sidepanel in Graph Editor: 

The current activity list panel looks like this: 

![image](https://user-images.githubusercontent.com/10279686/40003620-144ce458-5794-11e8-9d1f-3c3c0faa30cb.png)

We need the same visual aesthetics (alignment, padding, types) to the rest of sidepanels, for eg: this needs fixing: 

 
![image](https://user-images.githubusercontent.com/10279686/40003655-2e89a3ec-5794-11e8-89d2-f3b55a2a6b87.png)

^ 

1. Remove dependency from bootstrap (Remove bootstrap icons -> Move to MUI icons)
2. The entire panel content will be redone with MUI grid system (remove floats, absolute etc., code inspiration can be taken from activitity list panel)
4. Everything below Advanced needs fixing

![image](https://user-images.githubusercontent.com/10279686/40003661-331d391e-5794-11e8-921a-9a71df7801b5.png)

^ The upload panel can be combined with the learning items upload panel (if you fix one, both should get fixed)

**Comment by prastut** [comment]
- [ ] Preview Page: 

![image](https://user-images.githubusercontent.com/10279686/40003911-ccfeb4c2-5794-11e8-9f90-43a401d422c1.png)








- [ ] The preview panel control options has to be redone with MUI grid system (while phasing out boostrap): 
![image](https://user-images.githubusercontent.com/10279686/40003946-e4ed85ea-5794-11e8-93bc-8c9936e893e4.png)



- [ ] Modify boostrap styles for React JSON form schema -> MUI styles 
![image](https://user-images.githubusercontent.com/10279686/40004049-2361e46a-5795-11e8-899e-f11ba1cac9e6.png)

As you can see the add and close buttons need UX, positional as well as MUI styles fixing.

**Comment by prastut** [comment]
- [ ] The spinner has to be positioned in center (both horizontally and vertically using flex) (the one that you see for a very short term as soon as you refresh FROG)

**Comment by houshuang** [comment]
Don't worry too much about the advanced options at the bottom of the side panel, we'll probably remove/change these anyway.

**Comment by prastut** [comment]
- [ ] Graph Library (@romainAA combining graph library visual fixes here): 


![image](https://user-images.githubusercontent.com/10279686/40004900-fc9e3282-5796-11e8-9c65-7799ddd37556.png)
1. The graph library needs visual upgrade as the activity panel: 
2. Not able to scroll the entire length of the list, please see the activity list height CSS implementation
There is some height problem fixing that needs to be done ()

---

![image](https://user-images.githubusercontent.com/10279686/40004727-979b4118-5796-11e8-8ba5-d22395afa32e.png)

1. On preview page, there are 2 scrollbars inside graph library:

**Comment by anujanegi** [comment]
With regard to porting modals to material-ui, there seems to be a lot of files involved and the structure seems tough to be understandable for a newbie. Could you give a little overview?

**Comment by prastut** [comment]
@anujanegi what steps did you take to debug? The React Dev chrome extension is really helpful in getting to the particular component you see on the screen.

The way I go is: 

* Navigate to where you want to improve/fix etc. Taking an example, let's try to polish Learning Items modal issue as documented [here](https://github.com/chili-epfl/FROG/issues/1148#issue-322841531).
* Using the Chrome React Dev extension tool: 
![image](https://user-images.githubusercontent.com/10279686/42742304-6222f7a2-88d7-11e8-8c29-87cf28b2908b.png)
I was able to pinpoint what components are being used. As you can from the picture above, there is LearningItem component that is being created inside the Dialog. Now if I search LearningItem component there are tons of files that use it (specifically 34 results in 16 files). 
  * You could manually comb through each one of them with the pursuit that where is this component being created inside a Dialog. 
  * Or you can be a little smart. Familiarity with MUI is the key here in how it creates styles for components. In FROG we have a styles object inside each component which we use it to style the same. 

```
import * as React from 'react';
import { withStyles } from '@material-ui/core/styles';

const styles = {
   exampleStyle: {
      background: "red",
      fontSize: "2em", 
   }
}
  

class Example extends React.Component {
  render() {
    return <div className={classes.exampleStyle}>Hey</div>;
  }
}

export default withStyles(styles)(Example)

```
As you can from the above there is a withStyles HOC (Higher Order Component) which takes in a styles object and then uses it to style the Example Component. 

Coming back to our picture again where I highlight code inside the Chrome console.  
```
<div className="LearningItemChooser-dialog-443"> 
``` 
   Now I know that MUI creates these styles using a JSS compiler under the hood and the logic is generally 

```
<ComponentName-thenameoftheclasswhereyoudefinedthestyles-uniquehashsothatstylesdontmessupeachother>. 
```

With this info in mind: 
* ComponentName: LearningItemChooser
* The name of the class where you defined the styles: dialog. I used this to search.

![image](https://user-images.githubusercontent.com/10279686/42742660-22a714e8-88da-11e8-890d-63ddfc8a9b98.png)

So if you want to fix the Learning Items Modal styles you need to start from [here](https://github.com/chili-epfl/FROG/blob/develop/frog/imports/ui/LearningItem/LearningItemChooser.js#L76-L97) and traverse down.

**Comment by houshuang** [comment]
Hi @anujanegi, very happy to welcome you onto this project! I know that our code is sometimes convoluted, and we are hoping to gradually clean things up - I hate it when I have to jump back and forth between two files to follow the flow of code. However, the actual code defining modals is usually not so complex. If you have specific questions about a specific modal, or location in code, I'd be happy to help. 

When it comes to Learning Items, there are also other concerns, because the idea is that a Learning Item is an object that could look very different - an image, a table, a text, a simulation etc, and we're trying to be able to display Learning Items as part of many different kinds of activities. Here we need more work to come up with a common design pattern etc to make sure that they always look good, despite being so different.

**Comment by tusharpahuja** [comment]
I am working on fixing the preview panel control options.

**Comment by houshuang** [comment]
@tusharpahuja Great - please let me see your work as soon as possible - even if it's not finished, so I can make sure it goes in the right direction and provide any guidance. Let me know any questions you have.

**Comment by tusharpahuja** [comment]
@houshuang Sure! I will bring it to you as soon as possible.

UPDATE (Current status) ===
Phased out Bootstrap and used Material UI. @houshuang @prastut Please have a look at it.
![control](https://user-images.githubusercontent.com/18447348/45374553-1b62ec80-b610-11e8-96e8-1c90acbab979.png)

**Comment by prastut** [comment]
@tusharpahuja great job, though we also probably want to have better icon support from the material-ui icons. Nevertheless, you can push a PR for the same.

**Comment by prastut** [comment]
@houshuang this thread may have become outdated. Can you update this thread with what has been solved and what can newcomers solve?
