### ISSUE TITLE
Decreasing progress dashboard

### ISSUE THREAD

**Issue by lfaucon** [chili-epfl/FROG#1155]
Sometime when students go back in one activity, or when activity packages are not well implemented the progress dashboard receives logs of progress lower than previously received. This leads to weird situations. I'd suggest that the `mergeLog` function records progress using `max(log.payload.progress, previousProgress)`

**Comment by houshuang** [comment]
@lfaucon Is this still an issue? Do you want to update your previous PR?

**Comment by lfaucon** [comment]
Yes, I'll update my previous PR
