### ISSUE TITLE
Graph: Sometimes activities have length that is non-integer

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#116]
Look into the resize function, perhaps add a Math.round after the between, but ideally figure out why it happens.

**Comment by houshuang** [comment]
Relevant? http://stackoverflow.com/questions/3966484/why-does-modulus-operator-return-fractional-number-in-javascript

**Comment by lfaucon** [comment]
I do not think that this is what is causing the issue. This issue concerns approximation of decimal number, but should not occur with rounded integer. Most likely we forgot to use `Math.round` somewhere :)

[SMBC](http://www.smbc-comics.com/?id=2999 )

**Comment by lfaucon** [comment]
I observe right now that when I create an activity, the start time is not rounded.

**Comment by lfaucon** [comment]
Fixed.
