### ISSUE TITLE
New kind of learning item

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#1165]
Just writing this down to not forget it:

Currently, we've assumed that all learning items should have a Create method, be available in create lists etc. However, I'm suggesting a new kind of LI which cannot be created, but will be generated by for example operators like op-hypothesis. Imagine that an operator or activity could also register one or several learning items (a new field added to the operatorpackage learningitems?: LearningItemT[]). This learning item would only have a view/viewThumb function, but it would mean that any other activity would be able to display "hypotheses", or "Yahoo news items" etc. And they might also have toText and other functions to do something with the contents.

I'm further suggesting that in these cases when the content of the LI will never change (it doesn't make sense to allow editing of hypothesis annotations), that the payload of the LI be included in the object that has all the metadata, and there be no created sharedb document. 

Furthermore, for activities or operators that will only deliver learning items of a specific type, the fields of that learning item should be part of the outputDefinition somehow, so that we can filter or attach other rules based on the contents of the learning items.

**Comment by lfaucon** [comment]
> Currently, we've assumed that all learning items should have a Create method

Yes, you are right, learning items do not need a creator method or component if they can be created by operators.

> a new field added to the operatorpackage learningitems?: LearningItemT[]

The only problem I see with writing the code of this learning item in the operator package is that if we have two operators building the same learning item, the code would be duplicated. For example wouldn't Hypothesis LI be very similar to li-idea? Whenever we are able to, I suggest to reuse the LI types that already exist.

**Comment by houshuang** [comment]
Well, the code is minimal, right now the code for li-hypothesis is 27 lines(https://github.com/chili-epfl/FROG/pull/1183/files#diff-117f50bd974a7c2cf26afb967e746fec), and it could be even less if we standardize on a template format (for the compound learning items we want to edit in the GUI etc), basically just specifying the format... And going forwards I think we will want different fields, formats etc - for example with an RSS feed, we want tags, zooming to show the whole blog post, etc. 

There's also an issue with relying on other learning items existing - especially if they are coming from external packages. Right now we don't have a way to say that one package is dependent on another. Of course, now it's a mono-repo but it's still envisaged that in the future people can choose to install the packages they want. Of course we could add an external learning item in the package.json file of the activity that wants to reuse it, but ...
