### ISSUE TITLE
Preview in GraphEditor broken for some activities

### ISSUE THREAD

**Issue by romainAA** [chili-epfl/FROG#1174]
The preview functionality of the graphEditor needs a lot of fixes. It might partially come from using learning items that aren't in the default config of the activities.

- Quiz, Timed quizz, Ranking and Video Chat directly crash
![sans titre](https://user-images.githubusercontent.com/17392950/40656136-c7c86a56-6343-11e8-9cf1-5ed4febc2182.png)
- Stroop is broken
- CKB have its boxes completely lost 
- Classifier doesn't have any button to choose a category
- Dual activity have its images going places and button not responding
- Embedded website, Image Viewer, simple form, Text Component and Video Player just don't display their config (images, questions, site, …)
- Train is also broken when you start the questions

**Comment by houshuang** [comment]
@romainAA I think these should all work now - could you verify?

**Comment by romainAA** [comment]
@houshuang No, still none of these are working, all of those bugs are still here
