### ISSUE TITLE
LI-image: enable rotation (edit)

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#1204]

**Comment by romainAA** [comment]
Do you want a permanent rotation and rewriting it in the DB once rotated or just being able to rotate it when it's open as a modal after clicking on it ?

**Comment by romainAA** [comment]
Duplicate of #535

**Comment by houshuang** [comment]
It should be permanent, but I think the easiest would be to just store "rotation: x degrees" as metadata, and then use CSS to rotate it on the screen, rather than try to write a new file to the database...

This would mean adding an Editor component to li-image, which would show the image like in Viewer, but have a small rotate button, which would add the metadata (and then the renderer would just render it differently based on the metadata).
