### ISSUE TITLE
notebook feature

### ISSUE THREAD

**Issue by sharethewisdom** [chili-epfl/FROG#1286]
Hoping for some discussion, I just commented on youtube about the Wise integration video:

> A notebook is a must-have feature. Also, I think students would like to be able to create stuff across or outside of the scope of activities, that could be shared, cloned or downloaded selectively.

... and it would be nice to be able to import or export the notebook to/from Wise, and support offline availability.

**Comment by houshuang** [comment]
There are many things that would be nice, however we are a very small team and have to be selective (of course open to others contributing). I don't agree that a notebook is a must-have feature - it is useful in some specific pedagogical scenarios, but FROG is used for many other kinds of scripts than the typical science inquiry sequence that WISE is designed for. 

We're currently working on a collaborative rich-text editor which will also support learning items, this would allow us to have templates and have students insert not just images, like in WISE, but also rich representations like tables, etc. It probably won't function or look exactly like the WISE notebook, however.

Thank you for your suggestions.

**Comment by sharethewisdom** [comment]
Thank you for your response.

Sorry for the noise. I'm aware of the focus and of the practical difficulties. Most future users probably aren't developers. I'm not one myself, but I'll see if I can contribute (some css work, maybe) and if I can package FROG for Arch Linux.

I'd like to express some concerns though. If you'd be able to refer me to a discussion forum, I could delete this comment and put it there.

In my view there is too little focus on the effects of the medium on self-determination for pupils. What _other kinds of scripting_ do you mean, and using FROG, how could they -theoretically- support pupil's feeling of autonomy, competence and belonging?

Indeed these rich collaborative inquiries could maybe give learners some sense of belonging (although limited). But I have doubts when it comes to autonomy: ultimately the design of FROG suggests that it's the teacher who's in control. In my understanding pupils aren't really supposed to write these scripts, nor do they set goals or settle on the subject's meaning, significance, merit or worth. How autonomous can they be in the current interface? Can they choose a branch in the script, like in gaming, like with interactive fiction? Can they save discussions locally?

On the other hand, presenting content in playful, manageable and meaningful chunks with immediate feedback should improve the feeling of competence. But I have the impression that the pupil's social and creative efforts would get thrown away like on _"social"_ media.

**Comment by houshuang** [comment]
Hi,
I appreciate your comments. We do have a forum for FROG development here - https://spectrum.chat/frog-development - it's not very active, and it's focused more on the pure technicalities, but you are welcome to join.

I see your concerns about student agency etc - my background was with Peer2Peer university, which was an experiment in very open-ended collaborative learning. It's true that FROG right now is very teacher-centric, however in some of the use-cases that we are developing for - for example a lecture with 300 people - there isn't really that much scope for students to take control... One thing FROG does well is connect with external resources, so you could imagine students working on blog posts, editing wikis etc, and then coming together in a workshop-like mode to discuss and build meaning around those artefacts. In that case the teacher is more like a workshop-moderator...

It's also possible that parts of the FROG technology could be used by other teams to go in more radically open directions - a goal is to build reusable and modular technology that can be used for many purposes.

**Comment by sharethewisdom** [comment]
Hi,

I'll quickly comment here then. If one wants to make an exciting course for +300 students, it might be worth writing a text-based multi-player game with a huge decision tree, a natural language processing layer and a recurrent neural net. This allows the student to actively query a prompt in order to advance the story and complete a mission. This is the future of interactive fiction games. If you're interested see [this video](https://youtu.be/tSr4okYxwjk?t=21m20s). Accessibility concerns -an important topic for education- are also expressed.

> ... a lecture with 300 people - there isn't really that much scope for students to take control

My concerns are actually centered around this misconception (that's what I think it is). I feel that the same assumption is made at the department of education in my university. Truly, isn't there much of a scope? I can imagine **live feedback** with peer tutoring, natural language processing, school-wide or worldwide multi-lateral programmes, videochat, etc ... to grant a much better feeling of being able to express views and opinions, while the moderator role for the teacher can be retained.

> other teams to go in more radically open directions - a goal is to build reusable and modular technology that can be used for many purposes

Modularity is good. But widgets and protocols should get meaning. Why are activities seldom designed as true experiments? How do real-world scientists collaborate? Are students treated as consumers or creators? Why don't we allow them to work offline, when possible, away from tracking scripts? So yes one could take a _"more radical"_ approach, and I'm actually quite upset about the narrow scope on the psychological nature of learning applied in teacher-centered technologies that orchestrate with unchangeable timelines. It could be the student's choice to collaborate or discuss online. I don't mean that FROG should change into interactive fiction, but the point is that there may be activities that drive pupils more toward exploration.
