### ISSUE TITLE
[Editor] Building a basic Orchestration Graph

### ISSUE THREAD

**Issue by lfaucon** [chili-epfl/FROG#13]
- [x]  Gives choice between building Activities or Graphs
- [x]  Allow to select activities to build a very basic graph with the structure `A1 -> A2 -> ... -> An`

**Comment by mj2905** [comment]
Do you think that it would be better to reuse something like the filters in Repository to filter activities, and choose the one to put in the graph ? (I was thinking about a filterable field, like for the assignees in github, or using drag and drop, but each one requires an external library).

**Comment by lfaucon** [comment]
I trust your design choices and we encourage you to use external libraries. The selection of assignees on github is certainly a good choice
