### ISSUE TITLE
Add Licence File

### ISSUE THREAD

**Issue by juancarlosfarah** [chili-epfl/FROG#1385]
Can we add a Licence file so that it is clear which licence governs the use of FROG?

**Comment by houshuang** [comment]
https://github.com/chili-epfl/FROG#licensing

**Comment by houshuang** [comment]
https://github.com/chili-epfl/FROG/blob/develop/LICENSE

**Comment by juancarlosfarah** [comment]
Thanks for the quick response @houshuang !
