### ISSUE TITLE
teacher line causes error

### ISSUE THREAD

**Issue by jkolsen** [chili-epfl/FROG#1478]
When you put an activity on the teacher line, it is initially green but if anyone new uploads the graph or you run a session on the graph then the activity breaks. It still works in running but does not let you restart.

Also, the activity shows up in the projector view, which seems like the opposite place than where we would want teacher activities.
<img width="721" alt="screen shot 2018-10-12 at 10 22 37 am" src="https://user-images.githubusercontent.com/2493446/46857447-3ee4a700-ce09-11e8-8cc5-953d32214f75.png">

**Comment by houshuang** [comment]
Hi,

the error should definitively not happen and I have to look into it. The fact that it shows up "projector mode" is on purpose though - we just didn't have anywhere else to put it for now (we don't really have a "not-projector activity mode" for teacher's right now. Anyway I think we'll rethink a bit how we do this, integrating it into the orchestration mode, and possibly having a checkmark "show all activities" or only P3 etc... So far we haven't really used P4 in practice.

**Comment by houshuang** [comment]
Turns out this was because an upgrade function was run improperly, nothing to do with teacher line.
