### ISSUE TITLE
Sometimes crashes on creating new LI

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#1667]
Sometimes creating a new LI from the sidepanel, which I've changed to go directly to the new LI, crashes... I think this is a timing issue, whether the LI is created "in time" or not. We should wait for it to be created, rather than assume that it has been - but how to distinguish between LIs that are in the process of being created, vs LIs that we have to create ourselves, because there was a link from a non-existant LI?

<img width="471" alt="Screenshot 2019-04-29 at 11 31 14" src="https://user-images.githubusercontent.com/61575/56887659-726be380-6a72-11e9-8de4-66d635a098ad.png">

**Comment by dinomujki** [comment]
Yes, this is the problem with shareDB and using callbacks without something like await or Promises. I quickly moved the link redirect to be after the actual component state update which makes more sense and does provide more time for the update to actually happen, however does not really solve the underlying latency issue.
A possible approach is to handle this through a redirect-in-waiting in the component state. This would work by adding an expected redirect that waits for the wikiDoc and LI data to be created/updated and once this is done to actually run the redirect.
Another approach would be to have a loading screen until all the data is there and loaded and only then run the actual render (this might actually be worse UX). This would also require adding some temporary variable that stores some data on whether the currently opened page/LI should be created if it does not exists or just wait for it to be created by the op already submitted.

What do you think?
