### ISSUE TITLE
Error installing FROG

### ISSUE THREAD

**Issue by Mindtoeye** [chili-epfl/FROG#168]
Here are the commands I executed:

- get source

cd ~
git clone https://github.com/chili-epfl/FROG.git

- install meteor

cd /tmp
curl https://install.meteor.com/ | sh

- run the commands

cd ~
cd FROG
./initial_setup.sh

- output:

ERROR: [Errno 2] No such file or directory: 'install'
ERROR: [Errno 2] No such file or directory: 'install'
ERROR: [Errno 2] No such file or directory: 'install'
ERROR: [Errno 2] No such file or directory: 'install'
ERROR: [Errno 2] No such file or directory: 'install'

> ac-ck-board@1.0.0 build /home/vvelsen/oli/code/FROG/ac/ac-ck-board
> babel src --presets babel-preset-react,babel-preset-stage-0,babel-preset-es2015 --plugins babel-plugin-transform-class-properties,syntax-flow --out-dir dist && flow-copy-source src dist

ERROR: [Errno 2] No such file or directory: 'install'

> ac-form@1.0.0 build /home/vvelsen/oli/code/FROG/ac/ac-form
> babel src --presets babel-preset-react,babel-preset-stage-0,babel-preset-es2015 --plugins babel-plugin-transform-class-properties,syntax-flow --out-dir dist && flow-copy-source src dist

ERROR: [Errno 2] No such file or directory: 'install'

> ac-iframe@1.0.0 build /home/vvelsen/oli/code/FROG/ac/ac-iframe
> babel src --presets babel-preset-react,babel-preset-stage-0,babel-preset-es2015 --plugins babel-plugin-transform-class-properties,syntax-flow --out-dir dist && flow-copy-source src dist

> ac-jigsaw@1.0.0 build /home/vvelsen/oli/code/FROG/ac/ac-jigsaw
> babel src --presets babel-preset-react,babel-preset-stage-0,babel-preset-es2015 --plugins babel-plugin-transform-class-properties,syntax-flow --out-dir dist && flow-copy-source src dist

ERROR: [Errno 2] No such file or directory: 'install'
ERROR: [Errno 2] No such file or directory: 'install'

> ac-quiz@1.0.0 build /home/vvelsen/oli/code/FROG/ac/ac-quiz
> babel src --presets babel-preset-react,babel-preset-stage-0,babel-preset-es2015 --plugins babel-plugin-transform-class-properties,syntax-flow --out-dir dist && flow-copy-source src dist

src/config.js -> dist/config.js
src/board.js -> dist/board.js
src/index.js -> dist/index.js

> ac-text@1.0.0 build /home/vvelsen/oli/code/FROG/ac/ac-text
> babel src --presets babel-preset-react,babel-preset-stage-0,babel-preset-es2015 --plugins babel-plugin-transform-class-properties,syntax-flow --out-dir dist && flow-copy-source src dist

ERROR: [Errno 2] No such file or directory: 'install'
src/obs_container.js -> dist/obs_container.js
src/index.js -> dist/index.js
src/obs_detail.js -> dist/obs_detail.js

etc ...

**Comment by houshuang** [comment]
Hi,

sorry about that. I know we have a bit of a complex monorepo setup, however it should work, and we do have continuous integration which checks every commit (and the latest commit was successfully built by Codefresh, using exactly the same procedure). 

We have had some random bugs with yarn, one idea could be to replace yarn with npm in ./initial_setup, and try again. 

In general, this project is in a prototyping phase - we're still experimenting with APIs etc, so it's not actually usable for anything right now (we hope to run several experiments this fall, so we are certainly moving towards nailing down APIs etc). However, if you find any of this interesting, I'd love to chat with you.

**Comment by houshuang** [comment]
Closing for lack of feedback, feel free to re-open if you still have issues.
