### ISSUE TITLE
React layout not working in Safari?

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#193]
I load a scenario with two chat boxes, which works great in Chrome and Firefox, but in Safari I get nothing, but also no error message. 

<img width="721" alt="screen shot 2017-06-05 at 19 43 07" src="https://cloud.githubusercontent.com/assets/61575/26795793/393dea80-4a27-11e7-9957-e24e75b63c78.png">

**Comment by lfaucon** [comment]
The mosaic looked exactly like that without the css file `react-mosaic-component.css`. It might be the origin of this issue.

**Comment by houshuang** [comment]
Yeah, I get these errors. I've seen something about MIME types earlier in Chrome. We should figure out how to fix that. 

<img width="947" alt="screen shot 2017-06-06 at 10 17 04" src="https://cloud.githubusercontent.com/assets/61575/26819951/5dbda722-4aa1-11e7-8408-5ffde631e475.png">
