### ISSUE TITLE
Define and create user management interface

### ISSUE THREAD

**Issue by lfaucon** [chili-epfl/FROG#20]
- [ ] Define user hierarchy (teacher can create groups, can teacher also be a student in a different group, etc)
- [ ] Create user management interface, including CSV upload of user lists, generate "invite" keys so that students can easily sign up
- [ ] Various ways of logging in, username/password, but also unique URLs, email invitations etc

---

- **admin**: only the few ones administrating the project (4~5 people)
  - New admin accounts can be created manually by someone with rights to the deployment server
  - Can access `Admin` component
    - Can see all registered accounts from the Admin component 
    - Can delete/edit database items from the Admin component
    - Can add the **admin** or **teacher** tag to other accounts
  - Can access `Analytics` component for all sessions/graphs
  - Has all the rights of a teacher
- **teacher**: all the professor willing to create learning activities and edit orchestration graphs with us
  - Can access `Repository` and `Editor` component
  - Can access `Analytics` component for his own sessions
  - Can access the management interface for his own sessions
  - Has all the rights of a student
- **student**: anyone that connects to the website and creates an account
  - Can access the `Engine` component
  - Has the right to study

**Comment by houshuang** [comment]
teacher should have access to the analytics view of the session he/she "owns"... or maybe that should even be the default view for teacher once a graph "is running"?

**Comment by houshuang** [comment]
So we need a whole class management interface - can a teacher have multiple classes? How does he add/invite students, or do students first have to register before they can be added to a class? Some systems have invite codes - teacher generates an invite code or URL, which he gives to students, and students sign up themselves and are immediately added to the right class. Can a student be in multiple classes/groups at the same time?

**Comment by houshuang** [comment]
Jim's group might help with this
