### ISSUE TITLE
Revisiting operators/activities

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#232]
I think we should critically examine the operators/activities that we currently have. The goal should be operators and activities that give us a chance to test all the features of the engine, including various ways for data and social structure to flow etc, and to give us the opportunity to do interesting demos. 

It is important that the activities/operators are all up to date, with decent code, and that they are as interconnectable as possible.

## Activities
- ac-brainstorm 
  - no issues
- ac-chat       
  - this works great, could look nicer. 
- ac-ck-board   
  - this is good, because it demonstrates something more visual than the other activities. the most urgent change is to make it resolution-independent (so that boxes don't go out of focus when chat comes up on the side). this might involve adding some generic code to tell activities about their size. eventually should also add the possibility to add new ideas, configurable like in brainstorm.   
- ac-iframe     
  - no issues
- ac-text 
  - no issues, probably add choice between pure text/html/markdown in config later
- ac-video
  - no issues
- ac-form  and ac-quiz
  - I don't even remember which is which anymore, but we should definitively get rid of the one that asks us to list questions separated by comma. We might also want to add a proper quiz activity, which has some different modes - reveal immediately if question is correct, let student retry, etc. The nice thing would be that this would produce a score, which could be used for grouping/conditional activities, etc. Also configurable if all participants have to click submit, to submit?
  In the future, we might want a collaborative form where you can see one radio button for each student (each can only edit their own).
  Also, both should use the new collaborative form code.

We should also add a generic collaborative editing text activity.

## Operators
- op-aggregate-text
  - I'm not sure about this one... seems like if we have a list of items, a proper list view like Brainstorm is much better... Can you think of any use cases? We have an op-distribute which distributes lists of items, with quite a bit of choice, and op-select-best, which aggregates based on criteria... Could op-select-best be turned into a more generic aggregator (with several choices)?
- op-argue
  - I don't even remember what this was doing. Superfluous?
- op-create-groups
  - this is an attempt at making a pretty general group generator, with not too many config choices, but quite a bit of flexibility (as long as you want random). 
- op-distribute
  - again, attempt at making a generic distributor which can work with both p2 and p3 activities (as output), with a few config choices. 
- op-hypothesis
  - nice example of an asynchronous operator communicating with the outside world-
- op-jigsaw
  - could this functionality be added to op-create-group (optionally assign roles to groups)? 
- op-like-with-like
  - this is our only example of grouping based on input data, and not random, which is valuable - but it's obviously not very useful... I wonder if there is something a bit more sophisticated we could do, which would still work for demos... If there was a very simple sentiment analysis tool, that could let us put people in groups based on positive or negative messages :) or if we have proper quizzes, being able to group people based on a field and a greater than/lower than value. (ie. score > 50)...

**Comment by lfaucon** [comment]
- **ac-quiz** is a QCM and **ac-form** has open questions. ac-form is the one that ask for the comma separated configuration. ac-form can be configured to allow multiple submissions (not sure if it still works). Both forms get completed on submit. I believe it is good to have different types of quiz/form and I would suggest to keep both and improve them.

- **op-aggregate-text**: not to keep

- **op-argue** is the amazing operator that create the list of pairs (groups) to maximize their number of divergent answer at a MCQ. It needs to be updated to the new data types

-  **op-jigsaw**: I believe it might be better to keep it separated, for example I can imagine that we will like a different type of dealing with lack of students with the jigsaw constraints. Also if we imagine an other script with an operator that gives groups and colors to students. I think we don't want all of these to be merged within the default group formation operator.

- **op-like-with-like**: nice to keep. I don't have ideas to make it more interesting right now, but it could for example be useful if we want a prototype of interactive operator for group formation with an individual MCQ plugged in op-like-with-like. However I don't like its name, how about op-group-identical?

**Comment by houshuang** [comment]
Tasking @lfaucon with rewriting op-argue for the new API, all other ac/op should be up to date.
