### ISSUE TITLE
[Error] Cannot read property 'username' of undefined

### ISSUE THREAD

**Issue by lfaucon** [chili-epfl/FROG#27]
To investigate

![screen shot 2016-10-27 at 11 23 02](https://cloud.githubusercontent.com/assets/8818081/19761964/43361a8c-9c38-11e6-9da5-a35fba779916.png)

**Comment by houshuang** [comment]
cannot replicate

**Comment by KhalilMrini** [comment]
Cannot either

**Comment by lfaucon** [comment]
I dealt with it, seemed to happen when we had iddle user (connected long ago but without doing anything)
