### ISSUE TITLE
ScrollInterval not cancelled

### ISSUE THREAD

**Issue by lfaucon** [chili-epfl/FROG#274]
When dragging an operator or activity to the left and reaching minute=0 the scrollField disappear and cancelScroll sometimes is not triggered. That leaves us in a graph editor that always slides left. Not easy to reproduce because it sometime is and sometime isn't triggered.

```
const ScrollField = connect(
  ({
    store: { ui: { cancelScroll, ... } }
  }
...
      return (
        <rect
          onMouseEnter={() => scrollInterval(direction)}
          onMouseOut={cancelScroll}
          ...
        />
      )
  }
);
```

**Comment by houshuang** [comment]
@lfaucon Is this still an issue? I don't think I've ever triggered it.

**Comment by houshuang** [comment]
@lfaucon Closing this, let me know if it rears its ugly head again
