### ISSUE TITLE
New Activity Creation Steps

### ISSUE THREAD

**Issue by aperritano** [chili-epfl/FROG#283]
I'm trying to make a new activity that just echos the names of the students in a group called ac-hello. 

I started by copy ac-text and renaming it ac-hello, including its id
<img width="901" alt="screen shot 2017-06-27 at 12 16 16 pm" src="https://user-images.githubusercontent.com/219031/27600859-dfad3760-5b32-11e7-9ac5-a2374d96a6e1.png">

Next steps

1. How to insert groups into the activity? 
2. What are the steps to hook it up to be added as an activity? 
3. What would the graph look like in the graph editor? 
4. To add a new activity what steps are necessary?
     1. Add "name": "ac-hello", to package.json in ac-hello folder
     2. Add  "ac-hello": "*", to package.json in FROG > frog
     3. In FROG > frog > imports > activityTypes add the new activity to the list.
     4. initial_setup.sh be run again?

**Comment by houshuang** [comment]
Let me respond later, I should have automation ready for this by tomorrow.

**Comment by houshuang** [comment]
@aperritano 

you need to 
- copy an existing activity
- modify package.json (name), and the id in src/index.js (must be unique)
- symlink all the node_modules from root, including node_modules/.bin into the node modules
- symlink frog-utils into the package
- symlink the package into frog/node_modules
- add it to frog/package.json
- add it to frog/imports/activityTypes.js

I think that's all. If you do initial_setup, you still have to do the last two points.

**Comment by lfaucon** [comment]
I believe this has been solved by #291
