### ISSUE TITLE
Hot Editing Components

### ISSUE THREAD

**Issue by aperritano** [chili-epfl/FROG#285]
If a dev changes a component while meteor is running, how does one see those changes without running initial_setup.sh?

**Comment by aperritano** [comment]
i found run_and_watch.sh

One suggest would be to use gulp instead of bash scripts:
https://www.npmjs.com/package/gulp-watch

**Comment by houshuang** [comment]
Any advantage to this (gulp)? - the current approach works perfectly fine, and I would prefer to avoid even more tools etc unless clear advantage. Note that the only purpose of run_and_watch is to rebuild op/ac/frog-util packages (ES6 with Babel etc). They take src/ and turn it into dist/, which is exported. Meteor automatically picks up on file changes, and refreshes. If you're only editing the core frog package, you don't need run_and_watch.

**Comment by aperritano** [comment]
Gulp is a tool for automating tasks in a development work flow.
the advantage of gulp is that it mitigates having several shell scripts and puts all of these tasks in one locus of control. There are a number of plugins for it when you need to kick off task such as doing inital setup, run and watch, docker, jenkins, etc.. .

https://www.npmjs.com/package/gulp-jenkins
https://www.npmjs.com/package/gulp-docker

Something to consider in the future as more scripts and tasks are added to the workflow.
