### ISSUE TITLE
Defining Student View Activity Container

### ISSUE THREAD

**Issue by aperritano** [chili-epfl/FROG#286]
From the screenshot there is a component defining the top bar and windowing the two activities:

<img width="1220" alt="screen shot 2017-06-27 at 1 30 56 pm" src="https://user-images.githubusercontent.com/219031/27603821-00edec9e-5b3d-11e7-9e82-a04cd732e360.png">

How does one over load this structure make something like this:

<img width="788" alt="screen shot 2017-06-27 at 1 43 16 pm" src="https://user-images.githubusercontent.com/219031/27604349-a6206484-5b3e-11e7-8901-8198041a6536.png">

where is that component?

Then it is a top bar with a login and an brainstorm storm activity that supports multiple discussions.

**Comment by houshuang** [comment]
That top bar is the top bar of the entire app - shared between teachers and students. The idea is that it will only be available to the teacher, and show editing interface etc. Currently, all concurrent student activities are shown in the flexible layout mode. There is no implementation of a top-bar, or anything like that for students. But it feels like you're asking about three different things:

- Providing some consistent "branding" of FROG, for example a consistent CK header always showing above activities. 
  - As I said, the idea was to completely remove the bar for students, but we could certainly replace it with a generic FROG header, and make it very easy to replace this header component with a custom one for theming. (CK, or "EncoreLab" or whatever). The system could certainly expose the name/avatar of the currently logged in user, and let the custom design display it in different ways
- Choosing the session to work on
  - as mentioned, we currently don't have a login system at all. We need to come up with good abstractions, to make something pluggable. But it would be quite feasible to have an interface where you see the custom top bar for students (as mentioned above), and see a list of sessions that the student is assigned to (or which are designated as open, if the teacher chooses 'self-registration'), click on one, and you are in that session - ie. the top bar stays, but the main page is replaced by whichever activity is currently open.
- So we can let students choose between sessions (which could be different graphs, or different sessions based on the same graph). What we can currently not do is show a list of possible activities in a given session, and let the student choose which to engage with. We are planning more "asynchronous" / students-out-of-sync functionality in the future (also useful for MOOCs etc), but that will not happen anytime soon (fall, earliest).

**Comment by houshuang** [comment]
@aperritano I'm closing this, if you want to begin discussing one of the concrete issues I mentioned above, feel free to open a new, more targeted issue (and link back to this one).
