### ISSUE TITLE
run and watch script throwing errors

### ISSUE THREAD

**Issue by aperritano** [chili-epfl/FROG#290]
I took the ac-text activity and made a copy. ac-hello, including all the places was configured. What is this a symptom of? 

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ac-hello@1.0.0 watch: `watch 'npm run build' ./src`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ac-hello@1.0.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ajp/.npm/_logs/2017-06-28T15_09_22_604Z-debug.log

**Comment by aperritano** [comment]
when adding a new activity to the tree, run and watch does not do a npm install. node_modules under ac-hello is empty.

**Comment by houshuang** [comment]
This is not a bug, run_and_watch is not supposed to npm install, simply to continuously rebuild files that are modified. initial_setup runs install for all activities, and when adding a new activity, yarn install is literally a single command run once, no point in automating it (unless you're automating the whole adding activity workflow). Agree that we need better documentation of these things. (We're just getting used to having external people working on this :))

In similar cases, including the contents of the npm debug log might be useful.
