### ISSUE TITLE
Restart Graph Error from Teacher View

### ISSUE THREAD

**Issue by aperritano** [chili-epfl/FROG#293]
1. delete a graph and created a new one. 
2. teacher view did not update, hit stop and restart
3. Boom

another way. 1. start with a fresh graph. 2. create activity, users and assign. 3. run. 4. go back to the graph editor add a new activity. 5. hit restart, the new activity is deleted from graph, original one remains. 

I20170630-21:16:23.732(-5)? Exception while invoking method 'sessions.restart' TypeError: Cannot read property 'name' of undefined
I20170630-21:16:23.733(-5)?     at [object Object].addSession (imports/api/sessions.js:87:5)
I20170630-21:16:23.733(-5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
I20170630-21:16:23.734(-5)?     at packages/ddp-server/livedata_server.js:1666:15
I20170630-21:16:23.735(-5)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170630-21:16:23.736(-5)?     at packages/ddp-server/livedata_server.js:1664:30
I20170630-21:16:23.737(-5)?     at [object Object]._.extend.applyAsync (packages/ddp-server/livedata_server.js:1663:12)
I20170630-21:16:23.738(-5)?     at [object Object]._.extend.apply (packages/ddp-server/livedata_server.js:1611:26)
I20170630-21:16:23.738(-5)?     at [object Object]._.extend.call (packages/ddp-server/livedata_server.js:1593:17)
I20170630-21:16:23.739(-5)?     at [object Object].sessionsRestart (imports/api/sessions.js:152:24)
I20170630-21:16:23.739(-5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
I20170630-21:16:23.740(-5)?  => awaited here:
I20170630-21:16:23.741(-5)?     at Promise.await (/Users/ajp/.meteor/packages/promise/.0.8.9.120w11s++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:60:12)
I20170630-21:16:23.745(-5)?     at [object Object]._.extend.apply (packages/ddp-server/livedata_server.js:1624:22)
I20170630-21:16:23.745(-5)?     at [object Object]._.extend.call (packages/ddp-server/livedata_server.js:1593:17)
I20170630-21:16:23.746(-5)?     at [object Object].sessionsRestart (imports/api/sessions.js:152:24)
I20170630-21:16:23.747(-5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
I20170630-21:16:23.747(-5)?     at packages/ddp-server/livedata_server.js:719:19
I20170630-21:16:23.748(-5)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170630-21:16:23.748(-5)?     at packages/ddp-server/livedata_server.js:717:40
I20170630-21:16:23.748(-5)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
I20170630-21:16:23.749(-5)?     at packages/ddp-server/livedata_server.js:715:46

**Comment by houshuang** [comment]
The first issue I'm not sure about. In general, anytime there is an error specific to a graph, unless you can guarantee that it isn't an issue with any graph, attaching the exported graph to the bug report will be useful. @lfaucon can maybe look into it. 

On the second issue, currently when you switch to the teacher view to run a graph, and then switch back, what you are now editing by default is the session that has started. If you go back to teacher view to restart the session, actually the session is deleted, and a new session started from the original graph (which of course has not changed). I've been burnt by this in the past myself, and don't think it's an ideal flow, but perhaps it could be part of our discussion about the new UI - probably when wanting to edit a session, a teacher should stay in the teacher view, and the graph editor should only be for editing the underlying graphs etc?

**Comment by houshuang** [comment]
Closing, reopen if you have specific bugs with graph etc.
