### ISSUE TITLE
Conditional fields in ac/op config?

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#297]
As we are trying to build more general operators, we will have an increased need for conditional fields in configurations. (For example, do you want to sort items? By what fields). RJF does not support this natively, the suggestion is to use onChange to dynamically update the field definition (there are [some ideas](https://github.com/mozilla-services/react-jsonschema-form/issues/430) in the bug tracker). [Here's](https://github.com/mozilla-services/react-jsonschema-form/issues/522) another approach that uses a custom field (like Dario did for ShareDB) etc.

So one idea is to extend RJF a bit, for example extending the form format a bit, and then modifying that and having a form runner that implements conditionality etc. ANother is to enable React components for config and push that further (which we have planned to do anything for things like selecting regions on an image)...

Something similar will come in if we want to make an operator that can have complex conditionality (if X field is above Y value, open activity C, etc).

Would love your ideas/approaches..

**Comment by houshuang** [comment]
[react-jsonschema-form-layout](https://github.com/audibene-labs/react-jsonschema-form-layout) is an extension to RJF which both enables more complex layouts (Bootstrap-based, column/row), and conditional hiding of fields. Advantage would be avoiding having to write something yourself, disadvantage is that it adds complexity to the config declaration - right now we only export the schema, but this one uses uischema as well. Possibly we could spread the properties of config into Form, so that you could do config.schema, config.uiSchema etc... More complexity, but also more power :)

Another option would be to add a property to a form object, like

```
name: {
type: string,
title: 'Your name',
conditionalOn: needsName
}
```

(in the case of needsName being a boolean)

or

```
conditionalOn: (formData) => formData.lastname.length === 0
```

and write a custom wrapper for Form which uses onChange, walks the object, checks all conditions, and removes the non-matching ones from the schema given to the original RJF component. The advantage would be more compact config declarations, and I don't think it would be that hard to write...

We should also think about validation, optional fields etc. We both want to give the user feedback on what to enter, but also the graph editor/engine needs to know when a field is "complete" / runnable, and when not. 

Would love your thoughts @lfaucon

**Comment by lfaucon** [comment]
I'd rather like the approach of building an API for allowing both RJF-schema or react-component configuration. An activity package can then decide to use RJFL for the configuration but has to implement it itself. I like that way as it keeps the most simple cases as simple as possible.

I believe the only needed thing would be an `updateConfig` function. I can give it to do to Romain. He his doing good until now.

**Comment by houshuang** [comment]
I agree that we should support React components, and that would be an OK thing to implement, but I'm not so sure we should give up on conditional fields as a default yet. The thing is that we also need validation of forms, so we need optional fields etc - let's think more about this. 

Not sure what you mean by `updateConfig`? In my mind, `config` can either be an object or a ReactComponent (or to be less ambiguous, ActivityPackageT can either have configObj or configComponent (not sure how we can ask Flow to have at least one of two keys present, but not both - maybe first case is actually easier config: Object | React$Component).

The ReactComponent should not take as props the previous config (empty first time it's run, and an updateConfig function, which should be called on change (or maybe onChange function)). Or if it's fully controlled, the previous config would be updated every time you use updateConfig, so really `data` and `onChange`. Would be great to have an example, my immediate idea was an image with regions to click on (anatomy? map?), but I'm sure there are others.
