### ISSUE TITLE
createActivity.js npm start watch error

### ISSUE THREAD

**Issue by aperritano** [chili-epfl/FROG#298]
1. do:
node createActivity.js ac-ck-student ac-ck-student
out:
Activity created in './ac/ac-ck-student', and added to ./frog, all symlinks set up, yarn has installed and built all files.
Restart (or start) Meteor, run 'npm start watch' in ./ac/ac-ck-student/ and begin editing code. All changes will be
instantly picked up by FROG. Use 'git diff' to see all the changes that the script has made.

2. do:
/dev/FROG/ac/ac-ck-student> npm start watch
out:
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ajp/.npm/_logs/2017-07-02T01_08_04_929Z-debug.log
log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start', 'watch' ]
2 info using npm@5.0.4
3 info using node@v6.11.0
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at ReadFileContext.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:295:20)
4 verbose stack     at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:366:13)
5 verbose cwd /Users/aperritano/dev/FROG/ac/ac-ck-student
6 verbose Darwin 16.7.0
7 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "watch"
8 verbose node v6.11.0

**Comment by houshuang** [comment]
Sorry, should be `npm run watch`, only `npm start` used in root directory.
I know it's a bit confusing. I've updated the createActivity output message
in #301.
