### ISSUE TITLE
Auto Archiving/Exporting Session/Timeline Runs

### ISSUE THREAD

**Issue by aperritano** [chili-epfl/FROG#303]
This probably on the list somewhere, the idea of auto archiving sessions and all their data after each run of a timeline. For example, Prof. J. day 1 ends and the graph, session, and all student data are automatically exported and backed up on disk. Maybe this is part of a "Admin/Researcher View".  I'm  happy to participate in this discussion and help in this development.

**Comment by houshuang** [comment]
Currently, all work is stored in the database, and will never be overwritten in the future. Whether we want automatic backup of the whole system (in production, probably yes, but how) is one issue, seems to me you are more concerned about researchers getting access to the data? A few related issues:

- the ability to export the activity data from a single activity, for example all the quiz answers in activity 2 (this should be possible from the teacher view, in the same way you can inspect debug information now)
- the ability to export an entire session with all data (like a MOOC data dump), both for debugging, for moving a session, for restarting a session after a crash has been fixed, but possibly also for data analysis (tracked in #267)
- the original idea was to have very detailed and standardized logging which would in itself be enough for a researcher to analyze the learning. We have discussed quite a bit both the infrastructure, the formats, etc. This needs a lot more thinking.

**Comment by aperritano** [comment]
All excellent points. Specifically on the third one, logging, some types could be; 1)user interaction data (e.g., how many times he viewed evidence X) and 2) content data (e.g, what he answered for question Y), etc...

**Comment by houshuang** [comment]
Closing for now, feel free to open new more specific issues.
