### ISSUE TITLE
Quiz activity type

### ISSUE THREAD

**Issue by lfaucon** [chili-epfl/FROG#32]
'frogV2' does not handle Quiz activities anymore, but it will be easy to add it again.

@palexlee Could you share on this issue the json config file you have built? Thanks

**Comment by mj2905** [comment]
{
  "title": "MCQ",
  "type": "array",
  "items": {
    "type": "object",
    "title": "New Question",
    "required": [
        "title"
    ],
    "properties": {
      "title": {
        "type": "string",
        "title": "Question"
      },
      "answers": {
        "type": "array",
        "title": "Possible answers",
        "items": {
          "type": "object",
          "required": [
            "title"
          ],
          "properties": {
            "title": {
              "type": "string",
              "title": "Answer"
            },
            "answer": {
              "type": "boolean",
              "title": "This is an answer",
              "default": false
            }
          }
        }
      },
      "details": {
        "type": "string",
        "title": "Enter an explanation",
      }
    }
  }
}

**Comment by lfaucon** [comment]
```javascript
{
  title: "MCQ",
  type: "array",
  items: {
    type: "object",
    title: "New Question",
    required: [
      "title"
    ],
    properties: {
      title: {
        type: "string",
        title: "Question"
      },
      answers: {
        type: "array",
        title: "Possible answers",
        items: {
          type: "object",
          required: [
            "title"
          ],
          properties: {
            title: {
              type: "string",
              title: "Answer"
            },
            answer: {
              type: "boolean",
              title: "This is an answer",
              default: false
            }
          }
        }
      },
      details: {
        type: "string",
        title: "Enter an explanation",
      }
    }
  }
}
```

**Comment by KhalilMrini** [comment]
This can be closed?

**Comment by lfaucon** [comment]
Yes
