### ISSUE TITLE
Forever Graph Session

### ISSUE THREAD

**Issue by aperritano** [chili-epfl/FROG#325]
Does a teacher always have to cognizant of the ending of their session? Scenario; Professor X's class meets M W F. He creates a graph with a number of activities that he wants students to work on during the week and over the weekend for next Monday's class. How would this be supported with the current implementation? Would this be more of 'calendar' based scheduling of graphs? Maybe options for recurring days or weeks?

**Comment by houshuang** [comment]
Would the timing matter within the graphs, or would it simply be a number of activities all open simultaneously? We are thinking about how to implement more asynchronous graphs (more like a MOOC, where people come in at different times), and also thinking about how to deal with bouts of intensive orchestrated sessions, interspersed with a week of "homework" (asynchronous activities), etc. 

Of course the simplest solution is just to leave the session open - no action happens automatically (currently) - the clock is just an indicator, and if the teacher starts the graph, and then does nothing, it will stay open forever, on those open activities.

**Comment by houshuang** [comment]
Closing this, reopen with specifics.
