### ISSUE TITLE
Errors prevented startup after pulling #330-321, possible graph editor error.

### ISSUE THREAD

**Issue by aperritano** [chili-epfl/FROG#335]
after merging upstream changes and executing 'git clean -fdx', then './initial_setup.sh'. Every things built fine. 

/frog and running meteor, the following error: 

> meteor
[[[[[ ~/dev/FROG/frog ]]]]]                   

=> Started proxy.                             
=> Started MongoDB.                           
   Building for web.browser                  |
        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      
                                              
Unable to resolve some modules:

  "ac-ck-student" in /Users/aperritano/dev/FROG/frog/imports/activityTypes.js (web.browser)
  "ac-material-ui" in /Users/aperritano/dev/FROG/frog/imports/activityTypes.js (web.browser)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save ac-ck-student ac-material-ui
                                              
   Building the application                  /
        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      

        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 7. To find out the caller, grep for this
        message and change it to a `console.trace()`.
      
                                              
Unable to resolve some modules:

  "ac-ck-student" in /Users/aperritano/dev/FROG/frog/imports/activityTypes.js (os.osx.x86_64)
  "ac-material-ui" in /Users/aperritano/dev/FROG/frog/imports/activityTypes.js (os.osx.x86_64)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save ac-ck-student ac-material-ui
                                              
=> Errors prevented startup:                  
   
   While building for web.browser:
   imports/ui/GraphEditor/store/store.js:74:2: imports/ui/GraphEditor/store/store.js: Method has decorators, put the decorator plugin before the classes one.
   imports/ui/GraphEditor/store/activity.js:55:2: imports/ui/GraphEditor/store/activity.js: Method has decorators, put the decorator plugin before the classes one.
   imports/ui/GraphEditor/store/connection.js:43:2: imports/ui/GraphEditor/store/connection.js: Method has decorators, put the decorator plugin before the classes one.
   
=> Your application has errors. Waiting for file change.

**Comment by aperritano** [comment]
So part of this was that merge accidently removed the activity entries for activityTypes.js that I had for ac-ck-student and ac-material-ui. After adding them back and then git clean -fdx and intial_setup.sh the fixed reference for unable to resolve modules. However, `console.trace()` still floods the console and it fails

=> Errors prevented startup:                  
   
   While building for web.browser:
   imports/ui/GraphEditor/store/store.js:74:2: imports/ui/GraphEditor/store/store.js: Method has decorators, put the decorator plugin before the classes one.
   imports/ui/GraphEditor/store/activity.js:55:2: imports/ui/GraphEditor/store/activity.js: Method has decorators, put the decorator plugin before the classes one.
   imports/ui/GraphEditor/store/connection.js:43:2: imports/ui/GraphEditor/store/connection.js: Method has decorators, put the decorator plugin before the classes one.
   
=> Your application has errors. Waiting for file change.

**Comment by aperritano** [comment]
some process modified the .babelrc. This is the correct version:

**Comment by houshuang** [comment]
The .babelrc hasn't been changed since June 15th in this repo, so it should have been correct after git clean -fdx? 

Merging code when you have custom activities can be a bit annoying - I'm thinking of ways of having FROG automatically detect the activities etc that you have installed. For now, I guess you'll have to keep an eye on that when you merge. 

Seems like all the other issues were resolved, so I'm closing.
