### ISSUE TITLE
meteor long load times profiling

### ISSUE THREAD

**Issue by aperritano** [chili-epfl/FROG#377]
I'm plagued by frustratingly long load times even after a minor change like a console statement. First, there is a meteor restart time, then there is a browser reload time. I profiled the restart on a minor change. any input would be great.

thanks 

intensive tasks, it could be possible to optimize these/pre-compile

app/app.js..............................................2,522 ms (1)
I20170804-11:15:50.876(-5)? |    │  └─ require("./server/mergeData.js").....................2,460 ms (1)
I20170804-11:15:50.877(-5)? |    │     ├─ require("../imports/api/activities")..............2,156 ms (1)
I20170804-11:15:50.877(-5)? |    │     │  └─ require("./sessions")..........................2,121 ms (1)
I20170804-11:15:50.877(-5)? |    │     │     └─ require("./validGraphFn")...................2,118 ms (1)
I20170804-11:15:50.877(-5)? |    │     │        └─ require("../activityTypes")..............2,108 ms (1)

full log:

I20170804-11:15:36.806(-5)? | (#1) Profiling: Server startup
| (#24) Profiling: ProjectContext prepareProjectForBuild
|  Preparing project                         |
| ProjectContext prepareProjectForBuild...........................689 ms (1)
| ├─ _downloadMissingPackages                                     349 ms (1)
| └─ _buildLocalPackages                                          289 ms (1)
| 
| Top leaves:
| 
| (#24) Total: 689 ms (ProjectContext prepareProjectForBuild)
| 
| (#25) Profiling: Rebuild App               |
|                                            /
| Rebuild App...................................................9,133 ms (1)
| └─ files.withCache............................................9,133 ms (1)
|    ├─ compiler.compile(the app).................................117 ms (1)
|    │  └─ files.withCache........................................116 ms (2)
|    │     └─ compileUnibuild (the app)                           116 ms (2)
|    ├─ bundler.bundle..makeClientTarget........................7,738 ms (1)
|    │  └─ Target#make..........................................7,738 ms (1)
|    │     ├─ Target#_runCompilerPlugins..........................197 ms (1)
|    │     │  └─ plugin ecmascript                                100 ms (1)
|    │     ├─ Target#_emitResources.............................6,035 ms (1)
|    │     │  ├─ PackageSourceBatch.computeJsOutputFilesMap       693 ms (1)
|    │     │  └─ PackageSourceBatch#getResources................5,331 ms (93)
|    │     │     └─ PackageSourceBatch#_linkJS..................5,330 ms (93)
|    │     │        ├─ linker.fullLink..........................3,488 ms (1)
|    │     │        │  └─ linker Module#getPrelinkedFiles.......3,389 ms (1)
|    │     │        │     ├─ linker File#getPrelinkedOutput       861 ms (6667)
|    │     │        │     ├─ getPrelinkedFiles toStringWithSourceMap 2,343 ms (1)
|    │     │        │     └─ other linker Module#getPrelinkedFiles 184 ms
|    │     │        └─ other PackageSourceBatch#_linkJS         1,827 ms
|    │     ├─ Target#minifyJs                                   1,329 ms (1)
|    │     └─ sha1                                                141 ms (190)
|    ├─ bundler.bundle..makeServerTarget..........................429 ms (1)
|    │  └─ Target#make............................................429 ms (1)
|    │     ├─ Target#_runCompilerPlugins..........................131 ms (1)
|    │     │  └─ plugin ecmascript                                108 ms (1)
|    │     └─ Target#_emitResources...............................289 ms (1)
|    │        └─ PackageSourceBatch#getResources..................245 ms (97)
|    │           └─ PackageSourceBatch#_linkJS....................244 ms (97)
|    │              └─ linker.fullLink............................175 ms (1)
|    │                 └─ linker Module#getPrelinkedFiles.........165 ms (1)
|    │                    └─ getPrelinkedFiles toStringWithSourceMap 121 ms (1)
|    └─ bundler writeSiteArchive..................................840 ms (1)
|       └─ bundler writeTargetToPath..............................834 ms (2)
|          ├─ ClientTarget#write..................................522 ms (1)
|          │  └─ bundler writeFile................................502 ms (118)
|          │     └─ Builder#write.................................502 ms (118)
|          │        └─ files.writeFile                            485 ms (1)
|          └─ ServerTarget#write..................................312 ms (1)
|             └─ JsImage#write....................................287 ms (1)
|                └─ Builder#copyDirectory                         147 ms (24)
| 
| Top leaves:
| getPrelinkedFiles toStringWithSourceMap..................2,464 ms (2)
| other PackageSourceBatch#_linkJS.........................1,895 ms (190)
| Target#minifyJs..........................................1,329 ms (1)
| linker File#getPrelinkedOutput.............................875 ms (6916)
| files.writeFile............................................524 ms (6)
| other linker Module#getPrelinkedFiles......................214 ms (2)
| sha1.......................................................196 ms (2143)
| 
| (#25) Total: 9,133 ms (Rebuild App)
| 
I20170804-11:15:50.134(-5)? | (#1) Profiling: Server startup
I20170804-11:15:50.860(-5)? | 
I20170804-11:15:50.874(-5)? | Server startup................................................3,735 ms (1)
I20170804-11:15:50.875(-5)? | └─ Load server bundles........................................3,720 ms (1)
I20170804-11:15:50.875(-5)? |    ├─ packages/webapp.js........................................112 ms (1)
I20170804-11:15:50.875(-5)? |    │  └─ require("./node_modules/meteor/webapp/webapp_server.js") 112 ms (1)
I20170804-11:15:50.876(-5)? |    ├─ packages/http.js..........................................138 ms (1)
I20170804-11:15:50.876(-5)? |    │  └─ require("./node_modules/meteor/http/httpcall_server.js").137 ms (1)
I20170804-11:15:50.876(-5)? |    │     └─ Npm.require("request")                              137 ms (1)
I20170804-11:15:50.876(-5)? |    ├─ app/app.js..............................................2,522 ms (1)
I20170804-11:15:50.876(-5)? |    │  └─ require("./server/mergeData.js").....................2,460 ms (1)
I20170804-11:15:50.877(-5)? |    │     ├─ require("../imports/api/activities")..............2,156 ms (1)
I20170804-11:15:50.877(-5)? |    │     │  └─ require("./sessions")..........................2,121 ms (1)
I20170804-11:15:50.877(-5)? |    │     │     └─ require("./validGraphFn")...................2,118 ms (1)
I20170804-11:15:50.877(-5)? |    │     │        └─ require("../activityTypes")..............2,108 ms (1)
I20170804-11:15:50.877(-5)? |    │     │           ├─ require("ac-ck-student")                294 ms (1)
I20170804-11:15:50.877(-5)? |    │     │           ├─ require("ac-ck-poster")                 423 ms (1)
I20170804-11:15:50.877(-5)? |    │     │           ├─ require("ac-material-ui")               442 ms (1)
I20170804-11:15:50.878(-5)? |    │     │           ├─ require("ac-brainstorm")                304 ms (1)
I20170804-11:15:50.878(-5)? |    │     │           ├─ require("ac-video")                     216 ms (1)
I20170804-11:15:50.878(-5)? |    │     │           └─ require("ac-ck-board")                  200 ms (1)
I20170804-11:15:50.878(-5)? |    │     └─ require("./share-db-manager").......................215 ms (1)
I20170804-11:15:50.879(-5)? |    │        └─ require("sharedb-mongo")                         160 ms (1)
I20170804-11:15:50.879(-5)? |    └─ other Load server bundles                                 229 ms
I20170804-11:15:50.879(-5)? | 
I20170804-11:15:50.879(-5)? | Top leaves:
I20170804-11:15:50.902(-5)? | require("ac-material-ui")..................................442 ms (1)
I20170804-11:15:50.902(-5)? | require("ac-ck-poster")....................................423 ms (1)
I20170804-11:15:50.903(-5)? | require("ac-brainstorm")...................................304 ms (1)
I20170804-11:15:50.903(-5)? | require("ac-ck-student")...................................294 ms (1)
I20170804-11:15:50.903(-5)? | other Load server bundles..................................229 ms (1)
I20170804-11:15:50.903(-5)? | require("ac-video")........................................216 ms (1)
I20170804-11:15:50.903(-5)? | Npm.require("request").....................................206 ms (2)
I20170804-11:15:50.903(-5)? | require("ac-ck-board").....................................200 ms (1)
I20170804-11:15:50.904(-5)? | require("sharedb-mongo")...................................160 ms (1)
I20170804-11:15:50.904(-5)? | 
I20170804-11:15:50.904(-5)? | (#1) Total: 3,735 ms (Server startup)
I20170804-11:15:50.904(-5)? | 
=> Meteor server restarted

**Comment by houshuang** [comment]
I don't think there is any low-hanging fruit here, although if you find any, let us know. Here's another suggestion:

Can you try react-create-app (latest version), create a new app, boot it up, and make a change - is the reload time acceptable? I have been thinking about adding a very thin wrapper around activities so that you could develop a single activity without booting all of Meteor etc. Would be very easy to do ... I am guessing most of your time is spent on the look/interaction of activity packages, not on FROG core?

**Comment by aperritano** [comment]
re: react-create-app
much faster and with different output, instead of meteor restarting:

> meteor
[[[[[ ~/dev/experimental/simple-todos ]]]]]   

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
=> Client modified -- refreshing (x4)

re: interface
interface for now until  I get into permissions and groups

**Comment by aperritano** [comment]
I found a thread that discussions this issue: 

https://forums.meteor.com/t/meteor-auto-server-refresh/9549/18

one interesting point that was made: 

"All files you change and are on top level rebuild whole server.
Put your client side files in client folder and it will just refresh client without rebuilding server side.

And if you bundle your stable part of code into packages, also the client refresh times should improve."
