### ISSUE TITLE
Get data out of activities (externally)

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#390]
We need a standardized way of getting data out of activities, for example for a quiz, we want a CSV file of all the answers exported. What should be the interface for this? Right-clicking on a graph after an activity has completed and choosing download? How is the data formatted, is it just product, or is there a nicer way of exporting?

**Comment by romainAA** [comment]
We could do a nicer way, we would only need to add another field to every activity. Or maybe we could create an operator that take the input data and with his config knows where to save a new file. This way we could also define all format in this operator and choose which one we want with a radio button.
