### ISSUE TITLE
Wrong type in ac-chat mergeFunction

### ISSUE THREAD

**Issue by lfaucon** [chili-epfl/FROG#400]
When running a chat activity:

```
=> App running at: http://localhost:3000/
I20170817-10:22:19.630(2)? Exception in callback of async function: TypeError: obj.data.forEach is not a function
I20170817-10:22:19.702(2)?     at mergeFunction (/home/louisfaucon/FROG/ac/ac-chat/dist/index.js:55:12)
I20170817-10:22:19.702(2)?     at server/mergeData.js:55:13
I20170817-10:22:19.702(2)?     at runWithEnvironment (packages/meteor.js:1189:24)
```

**Comment by houshuang** [comment]
I remember we had problems with this in conjunction with Romain's activity - does this also happen with no incoming activityData?

**Comment by lfaucon** [comment]
Yes it happens when the empty data is `{}` instead of `[]`. 

My opinion is to not allow to have arrays for data as we can fake arrays with objects.

See discussion in #317

**Comment by houshuang** [comment]
Direct link to #309
