### ISSUE TITLE
RFC: Control operator

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#425]
An operator which receives the standard input, and produces a control describing which activities should be open for which students. 

Suggested type definitions, with `ActivityStructureT` being the output type of a Control Operator, and `structureDefT` already existing in types.js: 

```js
ActivityControlT = {
  structure: structureDefT,
  payload: {
    [attributeKey: string]: true
  }
}

ActivityStructureT = 
  | {'all': ActivityControlT} 
  | {[activityId: string]: ActivityControlT}
```

The idea is that the controls can either apply to all its connected activities, or can be listed separately for multiple activity IDs. Within ActivityControl, we apply a similar social structure to ActivityData, ie. all, groupingKeys, or individual, and for each attribute, we simply list them as true - if an attribute (all, groupingAttribute or student ID) is not listed, they do not have access to the activity. This allows us to easily check in the runner whether a given activity should be open or not.

Of course, access to social attributes etc must be checked by the graphValidator. However, in this case, any social structure can work with any activity - ie. an individual control structure can be applied to a p3 activity, excluding certain members of the class from a class activity. There will also be the possibility of selecting which incoming activity to map to which outcome in the config, through a special type of field (similar to the existing socialAttribute field).

**Comment by lfaucon** [comment]
After discussing with you, it seems very good. I updated the text concerning my understanding of the field `all`
