### ISSUE TITLE
[Editor] Form to create new activities

### ISSUE THREAD

**Issue by lfaucon** [chili-epfl/FROG#5]
In the Editor component create a form to add new activities:

The form should have the given fields:
- `id` TextInput
- `name` TextInput
- `type` Categorical (Choice between `quiz`, `video`, `lecture`)
- `plane` Categorical (Choice between `1`, `2`, `3`)
- `object` Depends on `type`
    * for `quiz`, TextInput for questions and choices
    * for `video`, chose one:
        + A field to chose a video to upload (write in the database the path of where the video is stored) 
        + TextInput for a youtube url
    * for `lecture`, TextInput for an url (example: The lecture is given on Hangout)

**Comment by houshuang** [comment]
Note that there are really good form components for React existing. Since we will probably need a bunch of forms in our app, it would be good to explore these and choose one, instead of building it all from hand (they offer things like validation, constraining to a certain kind of input, etc).

**Comment by lfaucon** [comment]
@palexlee other issues have been merged to the develop branch since you started working on issue-5, including few changes, in particular, the renaming of "quizz" to "quiz". I advise you to merge the develop branch to your current branch before going on.

**Comment by lfaucon** [comment]
I updated the issue description for the video activity type. We can also work with youtube urls for now, if it makes it easier for you.

**Comment by mj2905** [comment]
Just some questions about this issue : 
The field to choose the video to upload should choose among the user device files, or is it just some path that he/she inserts like some text ?
For the quiz, do we have to suppose that the user will put an answer from the choices, or do we have to check that he/she is not putting something wrong ?

**Comment by lfaucon** [comment]
For the video, you have to imagine a professor creating a learning activity. He will add a new video, so two things make sense for me:
- either the teacher has a video (saved on his computer) that he wants to upload on our platform. In that case, he should be presented with a way to browse his own file system to selected his desired video (or even better a drag and drop thingy), then the activity to insert in the database would be:
```
{ 
    ...,
    object: {
        path: "path/to/where/the/video/is/on/our/server"
    }
}
```

- either the teacher can copy paste the link to a youtube video (maybe after previously uploading his own video on Youtube)
```
{ 
    ...,
    object: {
        url : "www.youtube.com......"
    }
}
```

You should implement *at least one* of these solutions to create video learning activities

I hope I am clear in my explanation. Don't hesitate to ask more question :)

**Comment by mj2905** [comment]
Yeah, I see. Thank you for the clarification.
I think that I have finished to work with this issue (I just need to upload what I just did)

**Comment by mj2905** [comment]
Another question : We talked with Thanasis about the activities, and he said that there must be a duration for an activity. As we are using the activities for the graph creation, and that we will need this duration (the graph uses the time), do we implement this now ?

**Comment by lfaucon** [comment]
@mj2905 Yes, you are right. I left it out for now to not give you too much to do, but if you identify it as a requirement, it would be nice to add it for sure! The project is not very mature yet and we don't know all the requirements and final structure, so it is great if you can tell us what we need and the details we missed. Thanks
