### ISSUE TITLE
Fix UI for ac-induc

### ISSUE THREAD

**Issue by lfaucon** [chili-epfl/FROG#577]
A few points that should be improved

- The black box is not well contained under the top bar
- The submit button is not well centered
![screenshot from 2017-10-19 16-45-51](https://user-images.githubusercontent.com/8818081/31777437-54be7766-b4ee-11e7-91d3-849b411162e0.png)

- The toggle button does not have enough space and renders on two lines
![screenshot from 2017-10-19 16-56-50](https://user-images.githubusercontent.com/8818081/31777535-8c4a597a-b4ee-11e7-8e83-6c4388f0a1d5.png)

- Could you use something like [that](https://react-bootstrap.github.io/components.html#transitions-collapse) for the components under the toggle button so students can easily see that the question following the choice changes?

**Comment by romainAA** [comment]
@lfaucon closed ?
