### ISSUE TITLE
Modify engine to support new data structure (connections) and social structure

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#59]
Engine needs to be able to discern which operators are connected to an activity, and whether it has been run (recursively, ie. if an operator is connected to an other operator that has not been run, it has to be run as well). Might need to modify data structure for holding operator outputs.

**Comment by lfaucon** [comment]
As you are currently refactoring the `store`, I don't want to work on it anymore until you are done. I'll be thinking about how to modify the engine for our new type of graph.
