### ISSUE TITLE
Small problems with dashboards and preview

### ISSUE THREAD

**Issue by lfaucon** [chili-epfl/FROG#603]
## 1

From preview/ac-image, open 3 students and the dashboard. Switching from one example to the next does not refresh the dashboardView, for this we need to remove/add the dashboard

## 2

Uploads are for some reason not being counted

## 3

When using the preview from an activity in the graph and filling up the dashboard, then going to see the preview of that same activity type, the dashboard data has not been reinitialized.

**Comment by houshuang** [comment]
Bump

**Comment by houshuang** [comment]
@lfaucon I am adding a small fix for dashboard that didn't render properly the first example for ac-image. Other than that, I think this behaviour is OK - the dashboard just renders all the logs. We could empty all the logs for every time you switch examples, but sometimes it's nice to see multiple activities in the logs. It's easy enough to reset the data, and it should work reliably now. Reopen if you are unhappy with how this works.
