### ISSUE TITLE
Visual indicator of losing connection

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#617]
Right now there is no visual indicator (other than in console) if FROG looses connection, and in fact many things continue to work - but of course they don't get synced, once teacher tries to do something that relies on server functions, it will not be possible etc. Would probably be better to let the user know that he/she has been disconnected, and wait for reconnection before re-enabling the interface (needs a lot of testing).

**Comment by prastut** [comment]
Offline states can be quickly added if we have a reactive variable to update client, like how we have now with Error Boundary. 

Resources: 
* https://design.google/library/offline-design/
* https://developers.google.com/web/fundamentals/instant-and-offline/offline-ux
* https://material.io/guidelines/patterns/offline-states.html
