### ISSUE TITLE
Pretty Print JSON in Activity Preview 

### ISSUE THREAD

**Issue by aperritano** [chili-epfl/FROG#722]
![screen shot 2017-12-05 at 3 21 06 pm](https://user-images.githubusercontent.com/219031/33631426-2d2cf702-d9d0-11e7-89b0-08a288968a37.png)

**Comment by houshuang** [comment]
What you are seeing is literally the Activity Runner from your activity. So you can do what you want with that view. Including pretty printing. I recommend `json-stringify-pretty-compact` which is used in many other places already.
