### ISSUE TITLE
Code template is sometimes empty in ac-autocode preview

### ISSUE THREAD

**Issue by lfaucon** [chili-epfl/FROG#748]

**Comment by Keylas** [comment]
Does this bug happens for other examples than the first one ? It only happens to me when I click on the link from the list to open the preview (which shows example 0).
It can be brought back by clicking on another example, clicking back and resetting the reactive data. Then if the preview is closed and re-opened it will still have the code but reloading will generate the bug again.
If called directly, it happens with http://localhost:3000/preview/ac-autocode but not with http://localhost:3000/preview/ac-autocode/0?windows=1

**Comment by lfaucon** [comment]
Thank you for tracking that bug. It looks like it's not due to `ac-autocode` but to the Preview. I reproduce your observations when accessing it through the two links that you propose. @houshuang Do you see where it comes from?

**Comment by houshuang** [comment]
@lfaucon Is this still a problem?

**Comment by houshuang** [comment]
I think this is fixed now, reopen if still a problem
