### ISSUE TITLE
Adapt operators and activities to the new engine

### ISSUE THREAD

**Issue by lfaucon** [chili-epfl/FROG#75]
## Activities
- ck-board
    - [ ] robust
    - [ ] correct behavior
- form
    - [X] robust
    - [X] correct behavior
- iframe
    - [X] robust
    - [X] correct behavior
- jigsaw
    - [ ] robust
    - [X] correct behavior
- quiz
    - [ ] robust
    - [X] correct behavior
- text
    - [X] robust
    - [X] correct behavior
- video
    - [X] robust
    - [X] correct behavior

## Operators
- agg-ck-board
    - [ ] robust
    - [ ] correct behavior
- agg-text
    - [ ] robust
    - [ ] correct behavior
- argue
    - [X] robust
    - [X] correct behavior
- jigsaw
    - [X] robust
    - [X] correct behavior
- like-with-like
    - [X] robust
    - [X] correct behavior

**Comment by houshuang** [comment]
Are you happy with this one now? @lfaucon

**Comment by lfaucon** [comment]
Not yet. Still need to work on the activity types
