### ISSUE TITLE
ac-autocode does not verify configuration

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#755]
@Keylas Don't know if you've fixed this in your latest to PRs, but in the current code in develop, you are not checking required fields in the config - if I just create a new activity and don't enter any text, it validates the form (green), but when I try to run it, it crashes (cannot map etc)... Either make it robust to empty fields, or specify that certain fields are required etc in the config definition.

@lfaucon

**Comment by lfaucon** [comment]
Seems fixed
