### ISSUE TITLE
Issue log statements when activity begins

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#763]
Currently we log 'next.activity', and also almost all actual activities in ActivityRunners, but the suggestion is that we emit a log entry for each student in the StudentView/Runner, at the exact moment when the ActivityView is initiated. This will let us know precisely when students join, for students who join late (or joined the graph, logged out, and came back). 

The downside is that it will lead to a large amount of not very interesting log-entries, both in the actual log file, and arriving to the system at the same time.

For example, when we switched to the final activity in UNIL with an ac-image and an ac-quiz, the system would receive roughly 400 log messages almost at once (200 for each activity on the screen), and the log file would have 400 extra lines. 

Log files are not evaluated by reading through them anyway, so it's easy to filter. In terms of performance, we need to make sure this is OK - in the future we might go to some external log store like ElasticSearch anyway. However currently all log messages need to go through the central system to see if dashboards need to be updated etc - would we in the future have some messages that would be sent directly from clients to an external service, and not go through the server? This would add complexity.

**Comment by jkolsen** [comment]
Although this will add many extra lines, I think that it adds clarity to the orchestration to better understand the students/number of students who are active in the system. Although in synchronous activities, this may seem like over kill, especially on later activities in the graph, I think that it will also be very beneficial for asynchronous sessions.
