### ISSUE TITLE
[Engine] Accounts and collaboration

### ISSUE THREAD

**Issue by lfaucon** [chili-epfl/FROG#8]
In the Engine component:

- [x] require students to log in (https://www.meteor.com/tutorials/react/adding-user-accounts)

- [x] display list of currently connected students

- [x] create a very basic chat box

**Comment by lfaucon** [comment]
@KhalilMrini if you are done working on this issue, you should create a Pull Request and assign me to it for reviewing it, then we can merge it in develop.

**Comment by KhalilMrini** [comment]
@lfaucon Done :)
