### ISSUE TITLE
Fixing drawPath to look nicer

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#81]
Right now there is a problem when paths are drawn with the start later than the beginning, like this operator

![screen shot 2017-02-22 at 11 27 55](https://cloud.githubusercontent.com/assets/61575/23207572/0210e796-f8f2-11e6-9286-41f501b3767f.png)

should be quite easy to fix. 

Probably other things we can do too, for example links to activities should go to their front, not their back (like this link which merges with the activity body at the middle)

![screen shot 2017-02-22 at 11 29 28](https://cloud.githubusercontent.com/assets/61575/23207614/3183a07c-f8f2-11e6-8944-eb95b2dc20c5.png)

I'm not touching drawPath.js in my rewrite, so feel free to play with it :)

**Comment by lfaucon** [comment]
I will gladly play with draw path, once we have a bit more robust graph editor. I see only one path with the start later than the beginning which is the connection between the first individual quiz and the social operator and I can't see what is the problem with this connection.

The main problem I see concerns the second point that you raise; Connections **to** activities/operators should connect to the left side (input), while connections **from** activities/operators should connect to the right side (output).
