### ISSUE TITLE
Improve watch

### ISSUE THREAD

**Issue by prastut** [chili-epfl/FROG#874]
Watch is currently limited to only change in files. 

- [x] Transpile all files on start. 
- [x] Pipe new files when added.

**Comment by houshuang** [comment]
What does #2 mean? Doesn't it currently begin watching new files matching the glob automatically? Agree with #1.

**Comment by prastut** [comment]
Nope transpiling currently triggers only on change: https://github.com/chili-epfl/FROG/blob/develop/watch.js#L20. So in the case when you create a new file and then change it (like saving it -> it will trigger it). It misses the case when you copy a file and don't change it. 

Just have to add an event to also trigger when adding a new file.
