### ISSUE TITLE
Exporting unfinished graph with p2 activivities crashes

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#889]
If you have a session with p2 activities that have not yet run, and you try to export the graph, it will crash, because it is looking for the socialStructure of the activities that have not yet run (and their products/objects etc). We should avoid exporting activities that have not run yet.

**Comment by romainAA** [comment]
When I create a new graph, add just a chat activity in p2 and export the graph I don't get any error. It just download my .frog file. I never ran this graph in the process so I don't get where you get a crash
