### ISSUE TITLE
Mongo keys cannot have dots

### ISSUE THREAD

**Issue by lfaucon** [chili-epfl/FROG#890]
Mongo keys, even deep into a Mongo document structure, cannot have dots. This means we have to be very careful when using user-defined strings as keys.

Specific bug: The activityData from ac-show-social, when a name has dots.

More general: consider storing black-box data (config, product etc) as JSON.stringified. Downside is that it is harder to debug when looking in DB etc.

(this is Stian)

**Comment by houshuang** [comment]
@lfaucon We know the concrete issue here. The rule of thumb should be to never use student generated content as a key in an Object. Do we also need to for example wrap product in a JSON.stringify before writing to Mongo to ensure that an activity cannot mess up for a whole graph? We would have to make sure that we unwrap it everywhere we use it, etc...

**Comment by lfaucon** [comment]
Partially fixed by #891
