### ISSUE TITLE
Dealing with hot keys and input in Graph Editor

### ISSUE THREAD

**Issue by houshuang** [chili-epfl/FROG#95]
Previously we had a problem that we were listening to keyDown events on the entire window with GraphEditor, which would lead operators to be inserted when renaming graphs, etc.

I tried to fix this by attaching the keyDown events to the graph SVG instead, however I realized that the text input field (rename graph) is currently broken - it doesn't seem to accept any keypress, even if I remove all the keyDown code. Weird. Could you have a quick look?

**Comment by lfaucon** [comment]
I fixed the field `renameGraph`. the problem was due to `store.id` that had been renamed `store.graphID`.

We sill have the problem that social or product operators appear if we type `p`or `s`in that box

**Comment by houshuang** [comment]
Should be fixed by #97

**Comment by houshuang** [comment]
Reopen if bugs.
