### ISSUE TITLE
Error with preview of rich text

### ISSUE THREAD

**Issue by jkolsen** [chili-epfl/FROG#970]
When you first load a preset data, the rich text config is not preloaded.

When you type in the rich text box on the config you get a error: Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

(Update: I think it happens when you hit space bar at the end of the line.)

And when you try to refresh the page, you get an error: Uncaught SyntaxError: Unexpected end of JSON input

**Comment by lfaucon** [comment]
@jkolsen Is that fixed? If not, reopen
